---

- name: Aprovisionamiento de la máquina de desarrollo
  hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
    - commons
    - google-chrome
    - nodejs
    - sublime-text
    - visual-studio-code
    - tilix
    - terraform
    - kubectl
    - slack
