---
# tasks file for roles/sublime-text


- name: Instalar la clave GPG de Sublime-Text
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Agregar el repositorio de sublime-text
  apt_repository:
    repo: deb {{ item.repo }} {{ item.add }}
    state: present
    filename: "{{ item.file }}"
  with_items:
    - repo: https://download.sublimetext.com/
      add: apt/stable/
      file: sublime

- name: Install packages
  apt:
    state: installed
    pkg: "sublime-text"
    update_cache: yes
