---
# tasks file for roles/slack

- name: Instalar slack
  apt:
    # deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb
    name: slack-desktop
    update_cache: yes
    state: latest
